command=~/.config/sway/i3blocks/modules/$BLOCK_NAME

align=center
separator=true
separator_block_width=12
markup=pango

#[audac]
#min_width=50
#label=:
#instance=150
#interval=1
#markup=pango
#color=#ff1a8c

#[moc]
#min_width=50
#label=MC:
#instance=150
#interval=1
#markup=pango

[layout]
label=
interval=1
color=#66b5ef

[network]
label=
instance=wlp1s0
interval=10
color=#00ffff

[weather]
interval=600
markup=pango

[disk]
label=:
interval=300
color=#00ffff

[temp0]
label=
interval=5
command=cat /sys/class/thermal/thermal_zone0/temp | sed 's/\(.\)..$/.\1°C/'
color=#00ccff

[batterybar]
interval=30
markup=pango
color=#66b3ff

#[volume]
#label=
#interval=1
#<D-2><D-n><D-b><D-b>signal=1

[memory]
label=
interval=1
color=#77a8d7

[cpu]
label= 
interval=1
color=#6666ff

[time]
label=
command=date '+%H:%M  %d-%m'
interval=30
color=#7070db

#[backlight]
#label=
#interval=1
#color=#ffffcc

#[ports]
#label=
#interval=3600
#color=#ff1a1a
