#!/bin/sh
# Copyright (C) 2018 Minbari
# Display used, free and total memory with the help of freecolor utility

total_mem="$(free -m | awk '/^Mem/ {print $2}')"
used_mem="$(free -m | awk '/^Mem/ {print $3}')"
procent=$((100 * used_mem/total_mem))


if [ "${used_mem}" -lt "${total_mem}" ]; then
   echo "${used_mem} MB/${procent}%"
fi 
